sequences = {
    "heat_trace_sequence": {
        "syntax_format": "{HT_line}-{fluid_code}-{scovan_sequence_number}-{cable_number}",
        "name": "HT Line Sequence"
    },

    "heat_trace_component_sequence": {
        "syntax_format": "{electrical_component}-{fluid_code}-{scovan_sequence_number}-{cable_number}",
        "name": "HT Equipment Sequence"
    },
    "instrument_tag_sequence": {
            "syntax_format": "{instrument_type}-{scovan_sequence_number}",
            "name": "Instrument Tag"
        },
    "piping_line_no_insulation_sequence": {
        "syntax_format": "{line_size}-{fluid_code}-{piping_category}{piping_material}{corrosion_allowance}{service_modifier}-{scovan_sequence_number}",
        "name": "Piping Line without Insulation"
    },
    "piping_line_with_insulation_sequence": {
        "syntax_format": "{line_size}-{fluid_code}-{piping_category}{piping_material}{corrosion_allowance}{service_modifier}-{scovan_sequence_number}-{insulation_spec}",
        "name": "Piping Line with Insulation"
    },
    "piping_line_with_insulation_and_heat_trace_sequence": {
        "syntax_format": "{line_size}-{fluid_code}-{piping_category}{piping_material}{corrosion_allowance}{service_modifier}-{scovan_sequence_number}-{insulation_spec}-ET",
        "name": "Piping Line with Insulation and Heat Trace"
    },
    "valve_sequence": {
        "syntax_format": "{valve_size}{valve_type}-{class_code}{end_connection}-{body_material}{temperature_group}",
        "name": "Valve Sequence"
    }
}


component_mapping = {
    "electrical_component_mapping": {
        "PWR Kit": "MIQ-PJB",
        "RTD": "RTD",
        "Heat Trace PWR Kit": "HTPK",
        "Heat Trace Splice Kit": "HTSK",
        "name": "{electrical_component}"
    },
    "HT_mapping": {
        "name": "{HT_line}",
        "HT Line": "HT",
    }
}

end_connection_mapping = {
    "1": "Flanged - RF",
    "2": "Threaded",
    "3": "Socket Welded",
    "4": "SW x THRD",
    "5": "Flanged - FF",
    "6": "Butt Weld",
    "7": "Swagelok Grip Type Tube Fitting",
    "8": "Flanged - RTJ",
    "9": "BW x THRD",
    "10": "Chemflare",
    "name": "{end_connection}"
}
body_material_mapping = {
    "C": "Carbon Steel (105N/WCB)",
    "L": "Low Temperature Carbon Steel (LF2 CL1/LCC)",
    "S": "Stainless Steel (F316/CF8M)",
    "D": "Ductile Iron (Gr. 60-40-18 w/ Liner)",
    "H": "Hastelloy (N10276)",
    "W": "Duplex Stainless Steel (S31803/S32205)",
    "X": "Super Duplex Stainless Steel (S32750)",
    "P": "PFA",
    "V": "Polyvinyl Chloride (PVC) (Chemline)",
    "F": "Glass Reinforced Plastic (GRP) (Nil-Cor)",
    "K": "PVDF",
    "M": "Chrome-Moly",
    "name": "{body_material}"
}

temperature_group_mapping = {
    "A": "Metal Body Valves, Nonmetallic Seats (-45°C to 121°C)",
    "B": "Metal Body Valves, Nonmetallic Seats (-29°C to 121°C)",
    "C": "Metal Body Valves, Nonmetallic Seats (-29°C to 200°C)",
    "D": "Metal Body Valves, Nonmetallic Seats (-29°C to 315°C)",
    "E": "Metal Body Valves, Nonmetallic Seats (-45°C to 315°C)",
    "F": "Metal Body Valves, Nonmetallic Seats (-17°C to 121°C)",
    "Q": "Nonmetallic Body Valves, Nonmetallic Seats (-45°C to 110°C)",
    "R": "Nonmetallic Body Valves, Nonmetallic Seats (0°C to 50°C)",
    "5": "Metal Body Valves, Metal Seats (API Trim 5)",
    "8": "Metal Body Valves, Metal Seats (API Trim 8)",
    "12": "Metal Body Valves, Metal Seats (API Trim 12)",
    "16": "Metal Body Valves, Metal Seats (API Trim 16)",
    "50": "Metal Body Valves, Metal Seats (316 SS Trim)",
    "name": "{temperature_group}"

}


line_size_mapping = {
    "21": "21mm",
    "27": "27mm",
    "33": "33mm",
    "42": "42mm",
    "48": "48mm",
    "60": "60mm",
    "73": "73mm",
    "89": "89mm",
    "114": "114mm",
    "141": "141mm",
    "168": "168mm",
    "219": "219mm",
    "273": "273mm",
    "324": "324mm",
    "name": "{line_size}"
}




# Category / Rating Code (ASME Class & Connection Type)
piping_category_mapping = {
    "A": {"150"},
    "B": {"300"},
    "C": {"600"},
    "D": {"900"},
    "E": {"1500"},
    "F": {"2500"},
    "N": {"NONMETALLIC"},
    "L": {"LOCKRING"},
    "V": {"VICTAULIC"},
    "W": {"CAMLOCK"},
    "name": "{piping_category}"
}

# Piping Material
piping_material_mapping = {
    "1": "CARBON STEEL (A106 Gr. B)",
    "2": "LOW TEMPERATURE CARBON STEEL (A333 Gr. 6)",
    "3": "STAINLESS STEEL (A312 Gr. TP316/TP316L)",
    "4": "STAINLESS STEEL (A312 Gr. TP304/TP304L)",
    "5": "GALVANIZED CARBON STEEL (A106 Gr. B)",
    "6": "GALVANIZED LOW TEMPERATURE CARBON STEEL (A333 Gr. 6)",
    "7": "DUPLEX STAINLESS STEEL (S31803/S32205)",
    "8": "SUPER DUPLEX STAINLESS STEEL (S32750)",
    "9": "CARBON STEEL (A53 Gr. B w/ LINER)",
    "10": "HASTELLOY (N10276)",
    "11": "CHROME-MOLY",
    "12": "-",
    "50": "FIBERGLASS (NOV - RED THREAD)",
    "51": "FIBERGLASS (NOV - GREEN THREAD)",
    "52": "FIBERGLASS (NOV - CENTRICAST)",
    "53": "-",
    "80": "PERFLUOROALKOXY ALKANE (PFA) (CHEMLINE)",
    "name": "{piping_material}"
}

# Corrosion Allowance
corrosion_allowance_mapping = {
    "A": "0mm",
    "B": "1.6mm",
    "C": "3.2mm",
    "D": "4.8mm",
    "E": "6.4mm",
    "name": "{corrosion_allowance}"
}

instrument_identification_mapping = {
    "ANALYSIS PRIMARY": "A",
    "ANALYSIS ELEMENT": "AE",
    "ANALYSIS INDICATOR": "AI",
    "ANALYSIS CONTROLLER": "AC/AIC",
    "ANALYSIS TRANSMITTER": "AT",
    "ANALYSIS SWITCH": "AS()",
    "ANALYSIS ALARM": "AA()",
    "ANALYSIS SHUT DOWN": "ASD()",
    "ANALYSIS CONTROL VALVE OR REGULATOR": "AV",
    "ANALYSIS CONVERTER": "AY",
    "ANALYSIS DIFF. PRIMARY": "AD",
    "ANALYSIS DIFF. ELEMENT": "ADE",
    "ANALYSIS DIFF. INDICATOR": "ADI",
    "ANALYSIS DIFF. CONTROLLER": "ADC/ADIC",
    "ANALYSIS DIFF. TRANSMITTER": "ADT",
    "ANALYSIS DIFF. SWITCH": "ADS()",
    "ANALYSIS DIFF. ALARM": "ADA()",
    "ANALYSIS DIFF. SHUT DOWN": "ADSD()",
    "ANALYSIS DIFF. CONTROL VALVE OR REGULATOR": "ADV",
    "ANALYSIS DIFF. CONVERTER": "ADY",
    "BURNER FLAME PRIMARY": "B",
    "BURNER FLAME ELEMENT": "BE",
    "BURNER FLAME INDICATOR": "BI",
    "BURNER FLAME TRANSMITTER": "BT",
    "BURNER FLAME SWITCH": "BS()",
    "BURNER FLAME ALARM": "BA()",
    "BURNER FLAME SHUT DOWN": "BSD()",
    "BURNER FLAME CONTROL VALVE OR REGULATOR": "BV",
    "BURNER FLAME CONVERTER": "BY",
    "CONDUCTIVITY PRIMARY": "C",
    "CONDUCTIVITY ELEMENT": "CE",
    "CONDUCTIVITY INDICATOR": "CI",
    "CONDUCTIVITY CONTROLLER": "CC/CIC",
    "CONDUCTIVITY TRANSMITTER": "CT",
    "CONDUCTIVITY SWITCH": "CS()",
    "CONDUCTIVITY ALARM": "CA()",
    "CONDUCTIVITY SHUT DOWN": "CSD()",
    "CONDUCTIVITY CONTROL VALVE OR REGULATOR": "CV",
    "CONDUCTIVITY CONVERTER": "CY",
    "DENSITY PRIMARY": "D",
    "DENSITY ELEMENT": "DE",
    "DENSITY INDICATOR": "DI",
    "DENSITY CONTROLLER": "DC/DIC",
    "DENSITY TRANSMITTER": "DT",
    "DENSITY SWITCH": "DS()",
    "DENSITY ALARM": "DA()",
    "DENSITY SHUT DOWN": "DSD()",
    "DENSITY CONTROL VALVE OR REGULATOR": "DV",
    "DENSITY CONVERTER": "DY",
    "VOLTAGE (EMF) PRIMARY": "E",
    "VOLTAGE (EMF) ELEMENT": "EE",
    "VOLTAGE (EMF) INDICATOR": "EI",
    "VOLTAGE (EMF) CONTROLLER": "EC/EIC",
    "VOLTAGE (EMF) TRANSMITTER": "ET",
    "VOLTAGE (EMF) SWITCH": "ES()",
    "VOLTAGE (EMF) ALARM": "EA()",
    "VOLTAGE (EMF) SHUT DOWN": "ESD()",
    "VOLTAGE (EMF) CONTROL VALVE OR REGULATOR": "EV",
    "VOLTAGE (EMF) CONVERTER": "EY",
    "FLOW PRIMARY": "F",
    "FLOW ELEMENT": "FE",
    "FLOW INDICATOR": "FI",
    "FLOW CONTROLLER": "FC/FIC",
    "FLOW TRANSMITTER": "FT",
    "FLOW SWITCH": "FS()",
    "FLOW ALARM": "FA()",
    "FLOW SHUT DOWN": "FSD()",
    "FLOW CONTROL VALVE OR REGULATOR": "FV",
    "FLOW SELF-ACTUATED VALVE": "FCV",
    "FLOW CONVERTER": "FY",
    "FLOW DIFF. PRIMARY": "FD",
    "FLOW DIFF. ELEMENT": "FDE",
    "FLOW DIFF. INDICATOR": "FDI",
    "FLOW DIFF. CONTROLLER": "FDC/FDIC",
    "FLOW DIFF. TRANSMITTER": "FDT",
    "FLOW DIFF. SWITCH": "FDS()",
    "FLOW DIFF. ALARM": "FDA()",
    "FLOW DIFF. SHUT DOWN": "FDSD()",
    "FLOW DIFF. CONTROL VALVE OR REGULATOR": "FDV",
    "FLOW DIFF. SELF-ACTUATED VALVE": "FDCV",
    "FLOW RATIO INDICATOR": "FFI",
    "FLOW RATIO CONTROLLER": "FFC/FFIC",
    "FLOW RATIO SWITCH": "FFS()",
    "FLOW RATIO ALARM": "FFA()",
    "FLOW RATIO SHUT DOWN": "FFSD()",
    "FLOW RATIO CONTROL VALVE OR REGULATOR": "FFV",
    "FLOW QUANT. or EVENT INDICATOR": "FQI",
    "FLOW QUANT. or EVENT CONTROLLER": "FQC/FQIC",
    "FLOW QUANT. or EVENT TRANSMITTER": "FQT",
    "FLOW QUANT. or EVENT SWITCH": "FQS()",
    "FLOW QUANT. or EVENT ALARM": "FQA()",
    "FLOW QUANT. or EVENT SHUT DOWN": "FQSD()",
    "FLOW QUANT. or EVENT CONTROL VALVE OR REGULATOR": "FQV",
    "FLOW QUANT. or EVENT CONVERTER": "FQY",
    "GAGING (DIM) PRIMARY": "G",
    "GAGING (DIM) ELEMENT": "GE",
    "GAGING (DIM) INDICATOR": "GI",
    "GAGING (DIM) CONTROLLER": "GC/GIC",
    "GAGING (DIM) TRANSMITTER": "GT",
    "GAGING (DIM) SWITCH": "GS()",
    "GAGING (DIM) ALARM": "GA()",
    "GAGING (DIM) SHUT DOWN": "GSD()",
    "GAGING (DIM) CONTROL VALVE OR REGULATOR": "GV",
    "HAND CONTROLLER": "HC/HIC",
    "HAND SWITCH": "HS()",
    "HAND CONTROL VALVE OR REGULATOR": "HV",
    "HAND SELF-ACTUATED VALVE": "HCV",
    "CURRENT PRIMARY": "I",
    "CURRENT ELEMENT": "IE",
    "CURRENT INDICATOR": "II",
    "CURRENT CONTROLLER": "IC/IIC",
    "CURRENT TRANSMITTER": "IT",
    "CURRENT SWITCH": "IS()",
    "CURRENT ALARM": "IA()",
    "CURRENT SHUT DOWN": "ISD()",
    "CURRENT CONVERTER": "IY",
    "POWER PRIMARY": "J",
    "POWER ELEMENT": "JE",
    "POWER INDICATOR": "JI",
    "POWER CONTROLLER": "JC/JIC",
    "POWER TRANSMITTER": "JT",
    "POWER SWITCH": "JS()",
    "POWER ALARM": "JA()",
    "POWER SHUT DOWN": "JSD()",
    "POWER CONVERTER": "JY",
    "TIME INDICATOR": "KI",
    "TIME CONTROLLER": "KC/KIC",
    "TIME TRANSMITTER": "KT",
    "TIME SWITCH": "KS()",
    "TIME ALARM": "KA()",
    "TIME SHUT DOWN": "KSD()",
    "TIME CONTROL VALVE OR REGULATOR": "KV",
    "TIME CONVERTER": "KY",
    "LEVEL PRIMARY": "L",
    "LEVEL ELEMENT": "LE",
    "LEVEL INDICATOR": "LI/LG",
    "LEVEL CONTROLLER": "LC/LIC",
    "LEVEL TRANSMITTER": "LT",
    "LEVEL SWITCH": "LS()",
    "LEVEL ALARM": "LA()",
    "LEVEL SHUT DOWN": "LSD()",
    "LEVEL CONTROL VALVE OR REGULATOR": "LV",
    "LEVEL SELF-ACTUATED VALVE": "LCV",
    "LEVEL CONVERTER": "LY",
    "LEVEL DIFF. PRIMARY": "LD",
    "LEVEL DIFF. ELEMENT": "LDE",
    "LEVEL DIFF. INDICATOR": "LDI",
    "LEVEL DIFF. CONTROLLER": "LDC/LDIC",
    "LEVEL DIFF. TRANSMITTER": "LDT",
    "LEVEL DIFF. SWITCH": "LDS()",
    "LEVEL DIFF. ALARM": "LDA()",
    "LEVEL DIFF. SHUT DOWN": "LDSD()",
    "LEVEL DIFF. CONTROL VALVE OR REGULATOR": "LDV",
    "LEVEL DIFF. SELF-ACTUATED VALVE": "LDCV",
    "MOTOR SWITCH": "MS()",
    "MOTOR CONVERTER": "MY",
    "USER'S CHOICE PRIMARY": "N",
    "USER'S CHOICE ELEMENT": "NE",
    "TORQUE PRIMARY": "O",
    "TORQUE ELEMENT": "OE",
    "TORQUE INDICATOR": "OI",
    "TORQUE CONTROLLER": "OC/OIC",
    "TORQUE TRANSMITTER": "OT",
    "TORQUE SWITCH": "OS()",
    "TORQUE ALARM": "OA()",
    "TORQUE SHUT DOWN": "OSD()",
    "TORQUE CONTROL VALVE OR REGULATOR": "OV",
    "TORQUE CONVERTER": "OY",
    "PRESSURE PRIMARY": "P",
    "PRESSURE ELEMENT": "PE",
    "PRESSURE INDICATOR": "PI",
    "PRESSURE CONTROLLER": "PC/PIC",
    "PRESSURE TRANSMITTER": "PT",
    "PRESSURE SWITCH": "PS()",
    "PRESSURE ALARM": "PA()",
    "PRESSURE SHUT DOWN": "PSD()",
    "PRESSURE CONTROL VALVE OR REGULATOR": "PV",
    "PRESSURE SELF-ACTUATED VALVE": "PCV",
    "PRESSURE CONVERTER": "PY",
    "PRESSURE DIFF. PRIMARY": "PD",
    "PRESSURE DIFF. ELEMENT": "PDE",
    "PRESSURE DIFF. INDICATOR": "PDI",
    "PRESSURE DIFF. CONTROLLER": "PDC/PDIC",
    "PRESSURE DIFF. TRANSMITTER": "PDT",
    "PRESSURE DIFF. SWITCH": "PDS()",
    "PRESSURE DIFF. ALARM": "PDA()",
    "PRESSURE DIFF. SHUT DOWN": "PDSD()",
    "PRESSURE DIFF. CONTROL VALVE OR REGULATOR": "PDV",
    "PRESSURE DIFF. SELF-ACTUATED VALVE": "PDCV",
    "PRESSURE DIFF. CONVERTER": "PDY",
    "RADIATION PRIMARY": "R",
    "RADIATION ELEMENT": "RE",
    "RADIATION INDICATOR": "RI",
    "RADIATION CONTROLLER": "RC/RIC",
    "RADIATION TRANSMITTER": "RT",
    "RADIATION SWITCH": "RS()",
    "RADIATION ALARM": "RA()",
    "RADIATION SHUT DOWN": "RSD()",
    "RADIATION CONVERTER": "RY",
    "SPEED DIFF. INDICATOR": "SDI",
    "SPEED DIFF. CONTROLLER": "SDC/SDIC",
    "SPEED DIFF. SWITCH": "SDS()",
    "SPEED DIFF. ALARM": "SDA()",
    "SPEED DIFF. SHUT DOWN": "SDSD()",
    "SPEED DIFF. CONVERTER": "SDY",
    "SPEED FREQ. INDICATOR": "SI",
    "SPEED FREQ. CONTROLLER": "SC/SIC",
    "SPEED FREQ. TRANSMITTER": "ST",
    "SPEED FREQ. SWITCH": "SS()",
    "SPEED FREQ. ALARM": "SA()",
    "SPEED FREQ. SHUT DOWN": "SSD()",
    "SPEED FREQ. CONVERTER": "SY",
    "TEMPERATURE PRIMARY": "T",
    "TEMPERATURE ELEMENT": "TE",
    "TEMPERATURE INDICATOR": "TI",
    "TEMPERATURE CONTROLLER": "TC/TIC",
    "TEMPERATURE TRANSMITTER": "TT",
    "TEMPERATURE SWITCH": "TS()",
    "TEMPERATURE ALARM": "TA()",
    "TEMPERATURE SHUT DOWN": "TSD()",
    "TEMPERATURE CONTROL VALVE OR REGULATOR": "TV",
    "TEMPERATURE SELF-ACTUATED VALVE": "TCV",
    "TEMPERATURE CONVERTER": "TY",
    "TEMP. DIFF. PRIMARY": "TD",
    "TEMP. DIFF. ELEMENT": "TDE",
    "TEMP. DIFF. INDICATOR": "TDI",
    "TEMP. DIFF. CONTROLLER": "TDC/TDIC",
    "TEMP. DIFF. TRANSMITTER": "TDT",
    "TEMP. DIFF. SWITCH": "TDS()",
    "TEMP. DIFF. ALARM": "TDA()",
    "TEMP. DIFF. SHUT DOWN": "TDSD()",
    "TEMP. DIFF. CONTROL VALVE OR REGULATOR": "TDV",
    "TEMP. DIFF. SELF-ACTUATED VALVE": "TDCV",
    "MULTI-VARIABLE INDICATOR": "UI",
    "MULTI-VARIABLE CONTROLLER": "UC/UIC",
    "MULTI-VARIABLE CONTROL VALVE OR REGULATOR": "UV",
    "MULTI-VARIABLE CONVERTER": "UY",
    "VISC. OR VIBRATION PRIMARY": "V",
    "VISC. OR VIBRATION ELEMENT": "VE",
    "VISC. OR VIBRATION INDICATOR": "VI",
    "VISC. OR VIBRATION CONTROLLER": "VC/VIC",
    "VISC. OR VIBRATION TRANSMITTER": "VT",
    "VISC. OR VIBRATION SWITCH": "VS()",
    "VISC. OR VIBRATION ALARM": "VA()",
    "VISC. OR VIBRATION SHUT DOWN": "VSD()",
    "VISC. OR VIBRATION CONTROL VALVE OR REGULATOR": "VV",
    "VISC. OR VIBRATION CONVERTER": "VY",
    "WEIGHT PRIMARY": "W",
    "WEIGHT ELEMENT": "WE",
    "WEIGHT INDICATOR": "WI",
    "WEIGHT CONTROLLER": "WC/WIC",
    "WEIGHT TRANSMITTER": "WT",
    "WEIGHT SWITCH": "WS()",
    "WEIGHT ALARM": "WA()",
    "WEIGHT SHUT DOWN": "WSD()",
    "WEIGHT CONTROL VALVE OR REGULATOR": "WV",
    "WEIGHT CONVERTER": "WY",
    "UNCLASSIFIED PRIMARY": "X",
    "UNCLASSIFIED ELEMENT": "XE",
    "UNCLASSIFIED INDICATOR": "XI",
    "UNCLASSIFIED CONTROLLER": "XC/XIC",
    "UNCLASSIFIED TRANSMITTER": "XT",
    "UNCLASSIFIED SWITCH": "XS()",
    "UNCLASSIFIED ALARM": "XA()",
    "UNCLASSIFIED SHUT DOWN": "XSD()",
    "UNCLASSIFIED CONTROL VALVE OR REGULATOR": "XV",
    "UNCLASSIFIED CONVERTER": "XY",
    "USER'S CHOICE (Y) PRIMARY": "Y",
    "USER'S CHOICE (Y) ELEMENT": "YE",
    "USER'S CHOICE (Y) CONTROLLER": "YC/YIC",
    "USER'S CHOICE (Y) SWITCH": "YS()",
    "USER'S CHOICE (Y) SHUT DOWN": "YSD()",
    "USER'S CHOICE (Y) CONVERTER": "YY",
    "POSITION PRIMARY": "Z",
    "POSITION ELEMENT": "ZE",
    "POSITION INDICATOR": "ZI",
    "POSITION CONTROLLER": "ZC/ZIC",
    "POSITION TRANSMITTER": "ZT",
    "POSITION SWITCH OPEN": "ZSO",
    "POSITION SWITCH CLOSED": "ZSC",
    "POSITION ALARM": "ZA",
    "POSITION SHUT DOWN": "ZSD()",
    "POSITION CONVERTER": "ZY",
    "THERMOWELL": "TW",
    "PRESSURE INDICATING TRANSMITTER": "PIT",
    "TEMPERATURE INDICATING TRANSMITTER": "TIT",
    "POSITION SWITCH CLOSED": "XZI",
    "POSITION SWITCH OPEN": "XZIC",
    "FLOW SOLENOID ACTUATED VALVE": "FY",
    "TIME SOLENOID ACTUATED VALVE": "KY",
    "PRESSURE SOLENOID ACTUATED VALVE": "PY",
    "UNCLASSIFIED SOLENOID ACTUATED VALVE": "XY",
    "name": "{instrument_type}"
}

# Optional Service Modifier
service_modifier_mapping = {
    "1": "THRD PRIMARY CONSTRUCTION ON 1-1/2\" NPS & SMALLER",
    "2": "SW PRIMARY CONSTRUCTION ON 1-1/2\" NPS & SMALLER",
    "3": "GLYCOL SERVICE",
    "4": "STEAM SERVICE",
    "5": "SOUR SERVICE",
    "6": "DUCTING",
    "7": "COLD SERVICE",
    "8": "CRYOGENIC SERVICE",
    "9": "OXYGEN SERVICE",
    "10": "-",
    "name": "{service_modifier}"
}



class_code_mapping = {
    "A": 150,
    "B": 300,
    "C": 600,
    "D": 900,
    "E": 1500,
    "F": 2500,
    "name": "{class_code}"

}

fluid_code_mapping = {
    "AG": "ACID GAS/CO2 PRODUCT",
    "BA": "BREATHING AIR",
    "BFW": "BOILER FEED WATER",
    "BW": "BRACKISH WATER/BRINE",
    "BD": "BLOWDOWN",
    "C": "CATALYST",
    "CD": "CLOSED DRAIN",
    "CM": "COOLING MEDIUM",
    "DL": "DILUENT",
    "DW": "DRINKING/POTABLE WATER",
    "EXG": "FLUE GAS",
    "FG": "FUEL GAS",
    "HCL": "HYDROCARBON LIQUID",
    "HCV": "HYDROCARBON VAPOUR",
    "HM": "HEAT MEDIUM",
    "HO": "HOT OIL (PROCESS HEAT)",
    "HPF": "HIGH PRESSURE FLARE",
    "IA": "INSTRUMENT AIR",
    "IG": "INSTRUMENT GAS",
    "LAM": "LEAN AMINE",
    "LGL": "LEAN GLYCOL",
    "LO": "LUBE OIL",
    "LPF": "LOW PRESSURE FLARE",
    "LPG": "LIQUIFIED PETROLEUM GAS",
    "LPR": "LOW PRESSURE RELIEF",
    "M": "METHANOL",
    "N": "NITROGEN",
    "OD": "OPEN DRAIN",
    "PC": "PROCESS CONDENSATE",
    "PE": "PRODUCED EMULSION",
    "PG": "PRODUCED GAS",
    "PR": "PROPANE REFRIGERANT",
    "PW": "PRODUCED WATER",
    "RAM": "RICH AMINE/INTERSTAGE LINES",
    "RGL": "RICH GLYCOL",
    "RW": "RAW WATER",
    "S": "STEAM",
    "SC": "STEAM CONDENSATE",
    "SG": "SALES GAS",
    "SL": "SLOP OIL",
    "SO": "SALES OIL",
    "TW": "TREATED WATER/DEIONIZED WATER",
    "UA": "UTILITY AIR",
    "US": "UTILITY STEAM",
    "UW": "UTILITY WATER",
    "V": "VENT",
    "WC": "WASTE CHEMICAL",
    "WS": "WASTE WATER/STORM/SEWER",
    "name": "{fluid_code}"
}

valve_type_mapping = {
    "GA": "Gate",
    "BF": "Ball Full Port",
    "BR": "Ball Red Port",
    "CH": "Check",
    "GL": "GLOBE",
    "BU": "Butterfly",
    "PL": "PLUG",
    "NE": "Needle",
    "DI": "Diaphragm",
    "name": "{valve_type}"
}
scovan_sequence_number_mapping = {
    "scovan_sequence_number": r"^[A-Za-z]{1,2}\d{3,5}$",
    "name": "{scovan_sequence_number}"
}

cable_number_mapping = {
    "cable_number": r"^\d{1,2}[A-Za-z]?(?:/\d{1,2}[A-Za-z]?)?$",
    "name": "{cable_number}"
}
